# Generated by Django 3.0.5 on 2020-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=25, verbose_name='Имя пользователя')),
                ('user_last_name', models.CharField(max_length=25, verbose_name='Фамилия пользователя')),
                ('user_description', models.TextField(verbose_name='Описание профиля')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
