# Generated by Django 3.0.5 on 2020-05-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200513_1634'),
        ('user_accounts', '0002_auto_20200513_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Текущий проект'),
        ),
    ]
