# Generated by Django 3.0.5 on 2020-05-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200511_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
    ]
