# Generated by Django 3.0.5 on 2020-05-13 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200513_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 16, 34, 18, 589358), verbose_name='дата публикции'),
        ),
    ]
