# Generated by Django 3.0.5 on 2020-05-12 08:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20200511_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='project',
        ),
        migrations.RemoveField(
            model_name='member',
            name='project',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.AbstractUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_Ad',
            field=models.OneToOneField(default=projects.models.Ad, on_delete=django.db.models.deletion.CASCADE, to='projects.Ad'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(to='projects.Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_technologies',
            field=models.ManyToManyField(to='projects.Technology'),
        ),
    ]
