# Generated by Django 3.0.5 on 2020-05-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200512_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 14, 43, 54, 348496), verbose_name='дата публикции'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='технологии', to='projects.Technology'),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
