# Generated by Django 3.0.5 on 2020-05-13 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200513_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 16, 49, 37, 627508), verbose_name='дата публикции'),
        ),
    ]
