# Generated by Django 3.0.5 on 2020-05-18 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200518_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 40, 41, 556107), verbose_name='дата публикции'),
        ),
    ]
