# Generated by Django 3.0.5 on 2020-05-20 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200519_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Проект завершен'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 15, 6, 30, 481598), verbose_name='дата публикции'),
        ),
    ]
