# Generated by Django 3.0.5 on 2020-05-22 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200520_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members_count',
            field=models.IntegerField(default=1, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 21, 31, 12, 455414), verbose_name='дата публикции'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='project_set', to='projects.Technology', verbose_name='технологии'),
        ),
    ]
