# Generated by Django 3.0.5 on 2020-05-29 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200522_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 19, 29, 10, 760898), verbose_name='дата публикции'),
        ),
    ]
